### ISSUE TITLE
[Feat] type별 검색 기능 추가

### ISSUE THREAD

**Issue by onegqueen** [onegqueen/turntable#10]
# spotify api type별 검색 기능 

### 📑  **메인페이지 > 음악추천**
---
### ✏ TODO
- [x] 가수이름으로 가수목록 검색
- [x] 음악제목으로 음악 검색
- [x] 추천 알고리즘을 위한 시드장르 검색
---
각 타입별 음악정보를 검색하는 기능을 구현한다.
